import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/lib/reactquery";
import ProgressbarProvider from "@/lib/progressbar";
import Signin from "@/components/signin";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Watch Sub/Dub Anime Online For Free Without Ads on LuffyTaro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ReactQueryProvider>
          <Signin />
          <ProgressbarProvider>{children}</ProgressbarProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
