import type { Metadata } from "next";
import { Pathway_Extreme } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/lib/reactquery";
import ProgressbarProvider from "@/lib/progressbar";
import Signin from "@/components/signin";
import SocketProvider from "@/lib/socketProvider";

const pathway_extreme = Pathway_Extreme({
  weight: ["100", "200", "300", "400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Watch Sub/Dub Anime Online For Free Without Ads on LuffyTaro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={pathway_extreme.className}>
        <ReactQueryProvider>
          <SocketProvider>
            <Signin />
            <ProgressbarProvider>{children}</ProgressbarProvider>
          </SocketProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
